apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  volumes:
    - name: cache-volume
      emptyDir: {}
  initContainers:
    - name: init-container
      image: nginx
      command: ['sh', '-c', 'touch /workdir/test.txt']
      volumeMounts:
        - mountPath: /workdir
          name: cache-volume
  containers:
    - name: nginx
      image: nginx
      command: ['/bin/sh', '-c', 'if [ -e /workdir/test.txt ]; then sleep 60; else exit 1; fi']
      volumeMounts:
        - mountPath: /workdir
          name: cache-volume
