apiVersion: v1
kind: Pod
metadata:
  name: www-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerPort: 80
    - name: redis-container
      image: redis
    - name: memcached-container
      image: memcached
