apiVersion: v1
kind: Pod
metadata:
  name: env-secret
spec:
  containers:
    - name: env-secret
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username

# 確認
$ kubectl exec -it env-secret env | grep PASSWORD
