# secret after mount
$ kubectl create secret generic test-secret --from-literal=password=hogehoge

# 確認
$ kubectl get secret test-secret -o yaml | grep "password" | awk -F' ' '{print $2}' | base64 -d

apiVersion: v1
kind: Pod
metadata:
  name: volume-secret
spec:
  containers:
    - name: volume-secret
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /config
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret

# pods上の確認
kubectl exec -it volume-secret cat /config/username

